### ISSUE TITLE
database.json reponun içinde bulunmuyor

### ISSUE THREAD

**Issue by AenR** [hacettepeoyt/hu-cafeteria-bot#15]
Botu çalıştırıp menüyü öğrenmeye çalıştığımızda `database.json` ın bulunamadığı hatasını veriyor.

`FileNotFoundError: [Errno 2] No such file or directory: 'database.json'`

**Comment by furkansimsekli** [comment]
`update_db` taskını program ayağa kalktığında bir kere çalıştırmak mantıklı olabilir. Repoya eklersek belirli bir süre sonra güncelliğini yitirecek ve anlamı kalmayacak.
