### ISSUE TITLE
Vegan/Vegetarian Menu Has Been Moved Out

### ISSUE THREAD

**Issue by furkansimsekli** [hacettepeoyt/hu-cafeteria-bot#7]
## Problem
Recently [they split](http://www.sksdb.hacettepe.edu.tr/bidbnew/post.php?id=58319&title=vegan-menu-hk) vegetarian menu from the main one. They are publishing this menu in a way that different from the main menu.

## Solution
I'm thinking that there should be two different messages to be sent to [Telegram channel](https://t.me/hacettepeyemekhane). One is for main menu, other one is for vegetarian menu. We can add some icon indicators for the vegetarian one, so users wouldn't get confused.

### Development Details
Is there a proper XML file (like [main menu](http://sksdb.hacettepe.edu.tr/YemekListesi.xml)) that we can take advantage of? Scraping the HTML page shouldn't be the first choice because I remember when they first introduced allergen indicators to the menu, that day only Hacettepe Yemekhanecisi was alive :sunglasses:

**Comment by melikechan** [comment]
I have made a partial scan through SKSDB’s website (I just wondered if I could find a trace), and unfortunately, I can’t find any signs of a proper XML file. 
Maybe it would be better to ask someone you think knows about it, as I am not a _Hacettepe student_; it is more likely to get a negative answer (if I had found someone else). :/
If it is very urgent, scraping would be a quicker solution. If you don’t want to write, I can write a scraper in my free time as a substitution until we find the corresponding XML file.
(If you wonder why I have commented on your issue, I am still watching the repository :D and nobody commented on your issues, so I wanted to try to see if I can be helpful :>)

**Comment by furkansimsekli** [comment]
Thanks for the suggestions @melikechan , it's not urgent right now. Let's see how they publish the menu in the website for another few weeks. Maybe I can try to contact with the SKSDB department itself.

**Comment by furkansimsekli** [comment]
They still write vegan meals into normal menus. That's why there is no need to scrape another website.

**Comment by melikechan** [comment]
> They still write vegan meals into normal menus. That's why there is no need to scrape another website.
So, that means “vegan menu” will be fetched from the XML file?

**Comment by furkansimsekli** [comment]
> So, that means “vegan menu” will be fetched from the XML file?

Vegan menu isn't totally different thing from normal one, there is just one main meal difference and they write it with asterisk at the end of the menu. It was like this for a year and they will probably continue to do so.
